const languageConstants = {
  en: {
    getStarted: "Get Started",
    newToNetflix: "New to Netflix? ",
    alreadyRegistered: "Already Registered? ",
    signInNow: "Sign In now.",
    signUpNow: "Sign Up now.",
    signIn: "Sign In",
    signOut: "Sign Out",
    signUp: "Sign Up",
    homepage: "Homepage",
    homePageMainHeader: "Unlimited Movies, TV Series and more",
    homePageSubHeader: "Watch anywhere. Cancel at any time.",
    search: "Search",
    gptSearch: "GPT Search",
    gptSearchBarPlaceholder: "What would you like to watch today?",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    newReleases: "New Releases",
    topRatedMovies: "Top Rated Movies",
    trendingNow: "Trending Now",
    airingToday: "Airing Today",
    popularTvSeries: "Popular TV Series",
    topRatedTvSeries: "Top Rated TV Series",
    actionMovies: "Action Movies",
    crimeThrillerShowdown: "Crime Thriller Showdown",
    fantasyMovies: "Fantasy Movies",
    horrorMovies: "Horror Movies",
    thrillerMovies: "Thriller Movies",
    familyDrama: "Family Drama",
    sitcoms: "Sitcoms",
    crimeChronicles: "Crime Chronicles",
    dramaSeries: "Drama Series",
    realityTvShows: "Reality TV Shows",
    soapOperas: "Soap Operas",
    talkShows: "Talk Shows",
    home: "Home",
    movies: "Movies",
    tvSeries: "TV Series",
  },
  hi: {
    getStarted: "शुरू हो जाओ",
    newToNetflix: "नेटफ्लिक्स पर नए हैं? ",
    alreadyRegistered: "पहले से ही पंजीकृत? ",
    signInNow: "अब साइन इन करो।",
    signUpNow: "अभी साइनअप करें।",
    signIn: "साइन इन करें",
    signOut: "साइन आउट",
    signUp: "साइन अप करें",
    homepage: "मुखपृष्ठ",
    homePageMainHeader: "असीमित फिल्में, टीवी श्रृंखला और बहुत कुछ",
    homePageSubHeader: "कहीं भी देखो. किसी भी समय रद्द करें.",
    search: "खोज",
    gptSearch: "जीपीटी खोज",
    gptSearchBarPlaceholder: "आज आप क्या देखना चाहेंगे?",
    fullName: "पूरा नाम",
    emailAddress: "इमेल पता",
    password: "पासवर्ड",
    newReleases: "नई विज्ञप्तियां",
    topRatedMovies: "टॉप रेटेड फिल्में",
    trendingNow: "अब फैशन में है",
    airingToday: "आज प्रसारित हो रहा है",
    popularTvSeries: "लोकप्रिय टीवी श्रृंखला",
    topRatedTvSeries: "टॉप रेटेड टीवी सीरीज",
    actionMovies: "एक्शन फिल्मों",
    crimeThrillerShowdown: "क्राइम थ्रिलर शोडाउन",
    fantasyMovies: "काल्पनिक फिल्में",
    horrorMovies: "डरावने चलचित्र",
    thrillerMovies: "थ्रिलर फिल्में",
    familyDrama: "पारिवारिक नाटक",
    sitcoms: "सिटकॉम",
    crimeChronicles: "अपराध इतिहास",
    dramaSeries: "ड्रामा शृंखला",
    realityTvShows: "रियलिटी टीवी शो",
    soapOperas: "धारावाहिकों",
    talkShows: "चर्चा दर्शवितें",
    home: "घर",
    movies: "चलचित्र",
    tvSeries: "टीवी श्रृंखला",
  },
  kn: {
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    newToNetflix: "Netflix ಗೆ ಹೊಸಬರೇ? ",
    alreadyRegistered: "ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ? ",
    signInNow: "ಈಗ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    signUpNow: "ಈಗ ಸೈನ್ ಅಪ್ ಮಾಡಿ.",
    signIn: "ಸೈನ್ ಇನ್ ಮಾಡಿ",
    signOut: "ಸೈನ್ ಔಟ್",
    signUp: "ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    homepage: "ಮುಖಪುಟ",
    homePageMainHeader: "ಅನಿಯಮಿತ ಚಲನಚಿತ್ರಗಳು, ಟಿವಿ ಸರಣಿಗಳು ಮತ್ತು ಇನ್ನಷ್ಟು",
    homePageSubHeader: "ಎಲ್ಲಿಯಾದರೂ ವೀಕ್ಷಿಸಿ. ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ರದ್ದುಮಾಡಿ.",
    search: "ಹುಡುಕಿ",
    gptSearch: "GPT ಹುಡುಕಾಟ",
    gptSearchBarPlaceholder: "ನೀವು ಇಂದು ಏನನ್ನು ವೀಕ್ಷಿಸಲು ಬಯಸುತ್ತೀರಿ?",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಗುಪ್ತಪದ",
    newReleases: "ಹೊಸ ಬಿಡುಗಡೆಗಳು",
    topRatedMovies: "ಉನ್ನತ ದರ್ಜೆಯ ಚಲನಚಿತ್ರಗಳು",
    trendingNow: "ಈಗ ಟ್ರೆಂಡಿಂಗ್",
    airingToday: "ಇಂದು ಪ್ರಸಾರವಾಗುತ್ತಿದೆ",
    popularTvSeries: "ಜನಪ್ರಿಯ TV ಸರಣಿ",
    topRatedTvSeries: "ಉನ್ನತ ದರ್ಜೆಯ ಟಿವಿ ಸರಣಿ",
    actionMovies: "ಆಕ್ಷನ್ ಚಲನಚಿತ್ರಗಳು",
    crimeThrillerShowdown: "ಕ್ರೈಮ್ ಥ್ರಿಲ್ಲರ್ ಶೋಡೌನ್",
    fantasyMovies: "ಫ್ಯಾಂಟಸಿ ಚಲನಚಿತ್ರಗಳು",
    horrorMovies: "ಭಯಾನಕ ಚಲನಚಿತ್ರಗಳು",
    thrillerMovies: "ಥ್ರಿಲ್ಲರ್ ಚಲನಚಿತ್ರಗಳು",
    familyDrama: "ಕೌಟುಂಬಿಕ ನಾಟಕ",
    sitcoms: "ಸಿಟ್ಕಾಮ್ಸ್",
    crimeChronicles: "ಕ್ರೈಮ್ ಕ್ರಾನಿಕಲ್ಸ್",
    dramaSeries: "ನಾಟಕ ಸರಣಿ",
    realityTvShows: "ರಿಯಾಲಿಟಿ ಟಿವಿ ಶೋಗಳು",
    soapOperas: "ಧಾರವಾಹಿಗಳನ್ನು",
    talkShows: "ಟಾಕ್ ಶೋಗಳು",
    home: "ಮುಖಪುಟ",
    movies: "ಚಲನಚಿತ್ರಗಳು",
    tvSeries: "ಧಾರವಾಹಿ",
  },
  es: {
    getStarted: "Empezar",
    newToNetflix: "¿Nuevo en Netflix? ",
    alreadyRegistered: "¿Ya registrado? ",
    signInNow: "Regístrate.",
    signUpNow: "Regístrate ahora.",
    signIn: "Iniciar sesión",
    signOut: "Desconectar",
    signUp: "Inscribirse",
    homepage: "Página principal",
    homePageMainHeader: "Películas ilimitadas, series de TV y más",
    homePageSubHeader:
      "Mira en cualquier lugar. Cancelar en cualquier momento.",
    search: "Buscar",
    gptSearch: "Búsqueda GPT",
    gptSearchBarPlaceholder: "¿Qué te gustaría ver hoy?",
    fullName: "Nombre completo",
    emailAddress: "Dirección de correo electrónico",
    password: "Contraseña",
    newReleases: "Nuevos lanzamientos",
    topRatedMovies: "Películas mejor valoradas",
    trendingNow: "Siendo tendencia ahora",
    airingToday: "Transmitido hoy",
    popularTvSeries: "Serie de televisión popular",
    topRatedTvSeries: "Serie de televisión mejor valorada",
    actionMovies: "Películas de acción",
    crimeThrillerShowdown: "Enfrentamiento de suspenso y crimen",
    fantasyMovies: "Películas de fantasía",
    horrorMovies: "Películas de terror",
    thrillerMovies: "Películas de suspense",
    familyDrama: "Drama familiar",
    sitcoms: "Comedias de situación",
    crimeChronicles: "Crónicas del crimen",
    dramaSeries: "Series de drama",
    realityTvShows: "Programas de televisión de la vida real",
    soapOperas: "Telenovelas",
    talkShows: "Programas de entrevistas",
    home: "Hogar",
    movies: "Películas",
    tvSeries: "Series de TV",
  },
};

export default languageConstants;
