const languageConstants = {
  en: {
    getStarted: "Get Started",
    newToNetflix: "New to Netflix? ",
    alreadyRegistered: "Already Registered? ",
    signInNow: "Sign In now.",
    signUpNow: "Sign Up now.",
    signIn: "Sign In",
    signOut: "Sign Out",
    signUp: "Sign Up",
    homepage: "Homepage",
    homePageMainHeader: "Unlimited Movies, TV Series and more",
    homePageSubHeader: "Watch anywhere. Cancel at any time.",
    search: "Search",
    gptSearch: "GPT Search",
    gptSearchBarPlaceholder: "What would you like to watch today?",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    newReleases: "New Releases",
    topRated: "Top Rated",
    trendingNow: "Trending Now",
  },
  hi: {
    getStarted: "शुरू हो जाओ",
    newToNetflix: "नेटफ्लिक्स पर नए हैं? ",
    alreadyRegistered: "पहले से ही पंजीकृत? ",
    signInNow: "अब साइन इन करो।",
    signUpNow: "अभी साइनअप करें।",
    signIn: "साइन इन करें",
    signOut: "साइन आउट",
    signUp: "साइन अप करें",
    homepage: "मुखपृष्ठ",
    homePageMainHeader: "असीमित फिल्में, टीवी श्रृंखला और बहुत कुछ",
    homePageSubHeader: "कहीं भी देखो. किसी भी समय रद्द करें.",
    search: "खोज",
    gptSearch: "जीपीटी खोज",
    gptSearchBarPlaceholder: "आज आप क्या देखना चाहेंगे?",
    fullName: "पूरा नाम",
    emailAddress: "इमेल पता",
    password: "पासवर्ड",
    newReleases: "नई विज्ञप्तियां",
    topRated: "टॉप रेटेड",
    trendingNow: "अब फैशन में है",
  },
  kn: {
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    newToNetflix: "Netflix ಗೆ ಹೊಸಬರೇ? ",
    alreadyRegistered: "ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ? ",
    signInNow: "ಈಗ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    signUpNow: "ಈಗ ಸೈನ್ ಅಪ್ ಮಾಡಿ.",
    signIn: "ಸೈನ್ ಇನ್ ಮಾಡಿ",
    signOut: "ಸೈನ್ ಔಟ್",
    signUp: "ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    homepage: "ಮುಖಪುಟ",
    homePageMainHeader: "ಅನಿಯಮಿತ ಚಲನಚಿತ್ರಗಳು, ಟಿವಿ ಸರಣಿಗಳು ಮತ್ತು ಇನ್ನಷ್ಟು",
    homePageSubHeader: "ಎಲ್ಲಿಯಾದರೂ ವೀಕ್ಷಿಸಿ. ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ರದ್ದುಮಾಡಿ.",
    search: "ಹುಡುಕಿ",
    gptSearch: "GPT ಹುಡುಕಾಟ",
    gptSearchBarPlaceholder: "ನೀವು ಇಂದು ಏನನ್ನು ವೀಕ್ಷಿಸಲು ಬಯಸುತ್ತೀರಿ?",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಗುಪ್ತಪದ",
    newReleases: "ಹೊಸ ಬಿಡುಗಡೆಗಳು",
    topRated: "ಅತ್ಯುತ್ತಮವಾದ",
    trendingNow: "ಈಗ ಟ್ರೆಂಡಿಂಗ್",
  },
  es: {
    getStarted: "Empezar",
    newToNetflix: "¿Nuevo en Netflix? ",
    alreadyRegistered: "¿Ya registrado? ",
    signInNow: "Regístrate.",
    signUpNow: "Regístrate ahora.",
    signIn: "Iniciar sesión",
    signOut: "Desconectar",
    signUp: "Inscribirse",
    homepage: "Página principal",
    homePageMainHeader: "Películas ilimitadas, series de TV y más",
    homePageSubHeader:
      "Mira en cualquier lugar. Cancelar en cualquier momento.",
    search: "Buscar",
    gptSearch: "Búsqueda GPT",
    gptSearchBarPlaceholder: "¿Qué te gustaría ver hoy?",
    fullName: "Nombre completo",
    emailAddress: "Dirección de correo electrónico",
    password: "Contraseña",
    newReleases: "Nuevos lanzamientos",
    topRated: "Los más valorados",
    trendingNow: "Siendo tendencia ahora",
  },
};

export default languageConstants;
